apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    azure.workload.identity/use: "true"
    app: workload-demo
  name: workload-demo
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        app: workload-demo
    spec:
      containers:
      - image: quay.io/zhangchl007/workloadpython:v1
        imagePullPolicy: Always
        name: oidc
        env:
        - name: STORAGE_ACCOUNT_NAME
          value: "fusea1baa27d9bd44b269b8"
        - name: STORAGE_CONTAINER_NAME
          value: "pvc-7caab612-5410-4125-9db4-51fec72610de"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      serviceAccountName: workload-identity-sa